import {
  CANONICAL_AGENT_FILE,
  CONTEXT_DIR,
  CONTEXTUM_VERSION,
} from "./constants.js";
import type { RepoProfile } from "./detect.js";

const TODO_INLINE = "TODO: describe responsibility";
const TODO =
  "> TODO: fill in. Marked UNKNOWN by auto-generation — verify against code.";

const autoHeader = (title: string) =>
  `<!-- Generated by Contextum v${CONTEXTUM_VERSION}. Maturity: auto_generated — needs human review. -->\n\n# ${title}\n`;

export function agentsMd(profile: RepoProfile): string {
  return `# AGENTS.md — Canonical AI Instructions

This repository uses **Contextum** — a persistent AI context layer.
**This file is the single source of truth.** All other agent files
(\`CLAUDE.md\`, \`CODEX.md\`, \`GEMINI.md\`, Cursor/Copilot rules, etc.) are thin
wrappers that point here.

> Repository: **${profile.name}** · type: ${profile.type} · language: ${profile.primaryLanguage}

## Before changing code

1. Read \`${CANONICAL_AGENT_FILE}\` (this file).
2. Read \`${CONTEXT_DIR}/README.md\`.
3. Read \`${CONTEXT_DIR}/context.yml\`.
4. Read \`${CONTEXT_DIR}/code-map.md\`.
5. Read \`${CONTEXT_DIR}/integrations.md\`.
6. Read \`${CONTEXT_DIR}/business-features.md\`.
7. Read \`${CONTEXT_DIR}/change-impact.md\` **if the task is risky**.
8. Read \`${CONTEXT_DIR}/repository-boundaries.md\` **if unsure about scope**.

To navigate the code, use the dependency graph at \`${CONTEXT_DIR}/diagrams/code-graph.mmd\`
(and \`code-graph.json\`) when present — locate modules and trace imports instead of scanning.

**Do not scan the full repository** unless the context is stale or insufficient.
**Always verify context against the actual code** — context can drift.

## After implementing

- Update \`${CONTEXT_DIR}/freshness.md\` (and the changelog section there).
- Update \`${CONTEXT_DIR}/integrations.md\` if any contract changed.
- Update \`${CONTEXT_DIR}/business-features.md\` if behavior changed.
- Update \`${CONTEXT_DIR}/code-map.md\` if structure changed.
- Update \`${CONTEXT_DIR}/decisions.md\` if an architectural decision was made.
- Add to \`${CONTEXT_DIR}/relationships.md\` if you discovered a non-obvious cross-cutting link.

## Trust & honesty rules

- Prefer **low confidence** over hallucinated certainty.
- Treat **unknowns as first-class** — log them in \`${CONTEXT_DIR}/unknowns.md\`.
- Never fabricate integrations, contracts, or runtime behavior.

Run \`contextum validate\` and \`contextum doctor\` to check this layer.
`;
}

export function readme(profile: RepoProfile): string {
  const capabilities = profile.capabilities.length
    ? profile.capabilities.join(", ")
    : "UNKNOWN";
  return `${autoHeader("Repository Context")}
Human-readable summary of this repository's AI Context Layer, generated by Contextum.

## At a glance

| Field | Value |
| --- | --- |
| Name | ${profile.name} |
| Type | ${profile.type} |
| Primary language | ${profile.primaryLanguage} |
| Package manager | ${profile.packageManager} |
| Capabilities (detected) | ${capabilities} |
| Monorepo | ${profile.isMonorepo ? "yes" : "no"} |
| Docker | ${profile.hasDocker ? "yes" : "no"} |
| CI | ${profile.hasCi ? "yes" : "no"} |
| Infra-as-code | ${profile.hasInfra ? "yes" : "no"} |
| Tests detected | ${profile.hasTests ? "yes" : "no"} |

## What is this repository?

${TODO}

## The context layer

This \`${CONTEXT_DIR}/\` directory is persistent engineering memory for AI agents
and humans. See \`${CANONICAL_AGENT_FILE}\` at the repo root for read/update rules.

- \`context.yml\` — machine-readable index
- \`code-map.md\` — where things live
- \`business-features.md\` — what the system does, by capability
- \`integrations.md\` — inbound/outbound systems and contracts
- \`runtime.md\` — how to run, build, test, deploy
- \`data-model.md\` — data stores and schemas
- \`architecture-flows.md\` — runtime flows
- \`change-impact.md\` — blast radius of risky changes
- \`repository-boundaries.md\` — what belongs here vs. elsewhere
- \`decisions.md\` — architecture decision records
- \`relationships.md\` — non-obvious cross-cutting relationships (AI/human authored)
- \`unknowns.md\` — open questions (engineering backlog)
- \`lifecycle.md\` — trust state of this context
- \`freshness.md\` — when/how this was last validated
- \`agent-workflows.md\` — how multiple agents cooperate
`;
}

export function codeMap(profile: RepoProfile): string {
  const dirs = profile.topLevelDirs.length
    ? profile.topLevelDirs.map((dir) => `- \`${dir}/\` — ${TODO_INLINE}`).join("\n")
    : `- ${TODO_INLINE}`;
  return `${autoHeader("Code Map")}
Where important things live. Auto-detected top-level directories below; describe
each one's responsibility and verify before relying on it.

## Top-level layout

${dirs}

## Entry points

${TODO}

## High-value areas

${TODO}
`;
}

export function businessFeatures(): string {
  return `${autoHeader("Business Features")}
Capabilities this system provides, described from a business/runtime point of
view rather than by file. One section per feature.

## Feature template

\`\`\`
### <Feature name>
- Intent: what business need this serves
- Entry points: how it is triggered (route, queue, cron, CLI, UI)
- Core flow: step-by-step runtime behavior
- Contracts that must not break:
- Data touched:
- Risks / invariants:
- Owner: UNKNOWN
\`\`\`

## Features

${TODO}
`;
}

export function integrations(): string {
  return `${autoHeader("Integrations")}
Systems this repository talks to. Contracts here are safety-critical: agents
must not break them silently.

## Inbound (who calls us)

${TODO}

## Outbound (what we call)

${TODO}

## Data stores

${TODO}

## Contract notes

For each integration, capture: protocol, auth, idempotency, retry/timeout,
rate limits, and what a breaking change would look like.
`;
}

export function runtime(profile: RepoProfile): string {
  return `${autoHeader("Runtime")}
How to operate this repository. Fill UNKNOWN commands from package scripts,
Makefile, CI, or container definitions.

## Commands

| Action | Command |
| --- | --- |
| install | UNKNOWN |
| build | UNKNOWN |
| test | UNKNOWN |
| lint | UNKNOWN |
| dev | UNKNOWN |
| deploy | UNKNOWN |

Package manager detected: **${profile.packageManager}**.
Docker present: **${profile.hasDocker ? "yes" : "no"}** · CI present: **${profile.hasCi ? "yes" : "no"}**.

## Environment variables

${TODO}

## Local development

${TODO}
`;
}

export function dataModel(): string {
  return `${autoHeader("Data Model")}
Data stores, schemas, and the DTOs that cross boundaries.

## Stores

${TODO}

## Key schemas / tables / collections

${TODO}

## Invariants

State any data-level invariants that must always hold (uniqueness, ordering,
no-double-write, money precision, etc.).

${TODO}
`;
}

export function architectureFlows(): string {
  return `${autoHeader("Architecture Flows")}
Runtime flows through the system. Prefer Mermaid so agents can reason about
direction. See \`${CONTEXT_DIR}/diagrams/\` for diagram sources.

## Primary flow

\`\`\`mermaid
flowchart TD
  A[Trigger] --> B[Handler]
  B --> C[Domain logic]
  C --> D[(Data store)]
  C --> E[External integration]
\`\`\`

${TODO}
`;
}

export function changeImpact(): string {
  return `${autoHeader("Change Impact")}
Blast radius of risky changes. Read this before touching anything that could
affect money, data integrity, contracts, or downstream systems.

## High-risk areas

${TODO}

## Blast-radius checklist

- What downstream systems depend on this?
- What contracts could break?
- What invariants could be violated?
- Is there a migration or backfill implication?
- What is the rollback plan?
`;
}

export function repositoryBoundaries(): string {
  return `${autoHeader("Repository Boundaries")}
What belongs in this repository — and what does not. Helps agents avoid
scope creep and cross-repo coupling.

## In scope

${TODO}

## Out of scope (lives elsewhere)

${TODO}

## Cross-repo contracts

${TODO}
`;
}

export function decisions(): string {
  return `${autoHeader("Architecture Decisions")}
Architecture Decision Records (ADRs). Each entry: context, decision,
consequences, evidence.

## ADR template

\`\`\`
### DEC-001: <title>
- Status: proposed | accepted | superseded
- Context:
- Decision:
- Consequences:
- Evidence (files/PRs):
\`\`\`

## Decisions

${TODO}
`;
}

export function relationships(): string {
  return `${autoHeader("Relationships")}
First-class relationships between concepts, modules, invariants, and domains in
this system — especially the **non-obvious** ones that are not visible from
imports, types, or names.

Structural links (who imports whom, who defines what) already live in the code
graph (\`diagrams/code-graph.*\`) and the symbol index (\`diagrams/code-symbols.json\`).
**Do not duplicate them here.** This file captures connections that require
understanding to see: shared invariants, implicit contracts, cause/effect across
modules, hidden coupling, and cross-domain analogies.

Each relationship is a self-contained entry so it can stand on its own and be
retrieved independently.

## Relationship template

\`\`\`
### <A> ⇄ <B>
- Type: shared-invariant | implicit-contract | cause-effect | data-flow | hidden-coupling | analogy
- Relationship: how A and B are connected
- Why it matters: what breaks or gets misunderstood if this link is missed
- Evidence: files / symbols
- Confidence: low | medium | high
- Non-obvious: yes | no   (yes = not derivable from imports, types, or names)
\`\`\`

## Relationships

${TODO}
`;
}

export function unknowns(): string {
  return `${autoHeader("Unknowns")}
Open questions are **engineering backlog, not failure**. Logging an unknown is
better than guessing.

## Business unknowns

${TODO}

## Runtime unknowns

${TODO}

## Integration unknowns

${TODO}

## Ownership unknowns

${TODO}

## Testing unknowns

${TODO}

## Production unknowns

${TODO}
`;
}

export function lifecycle(): string {
  return `${autoHeader("Context Lifecycle")}
Trust state of this context layer.

| State | Meaning |
| --- | --- |
| auto_generated | created by tool/agent — needs review |
| reviewed | a human or architect reviewed it |
| trusted | repeatedly validated and used |
| stale | known outdated |
| deprecated | no longer maintained |

**Current state: \`auto_generated\`.**

Promote the state as the context is reviewed and proven. Demote to \`stale\`
when the code drifts ahead of the context.
`;
}

export function freshness(date: string): string {
  return `${autoHeader("Freshness")}
Validation status and change log for this context layer.

## Status

| Field | Value |
| --- | --- |
| Generated at | ${date} |
| Generated by | contextum v${CONTEXTUM_VERSION} |
| Maturity | auto_generated |
| Last validated | ${date} |

## Stale triggers

Regenerate or review when any of these happen:

- source code changed without a context update
- runtime config changed
- dependency graph changed
- an API/integration contract changed

## Changelog

- ${date} — initial context layer generated by Contextum.
`;
}

export function agentWorkflows(): string {
  return `${autoHeader("Agent Workflows")}
How multiple AI agents cooperate on this repository. Generic by design — adapt
the roles to your team.

## Feature implementation workflow

1. **Business analyst agent** — clarifies intent, updates \`business-features.md\`.
2. **Developer agent** — implements code, respects \`repository-boundaries.md\`.
3. **Reviewer agent** — reviews the diff for correctness, concurrency, security.
   *Review-only: must not modify code, only report findings.*
4. **Architect agent** — validates architecture, updates \`decisions.md\`.
5. **Tester agent** — adds tests, runs unit/integration/load checks.
6. **Context maintainer** — updates \`freshness.md\` and the changelog.

## Rules

- The reviewer never writes code.
- Every behavior-changing step updates the relevant context file.
- Unknowns go to \`unknowns.md\`, never get silently guessed.
`;
}

export function diagramRuntimeFlow(): string {
  return `flowchart TD
  Trigger[Inbound trigger] --> Handler
  Handler --> Domain[Domain logic]
  Domain --> Store[(Data store)]
  Domain --> External[External integration]
`;
}

export function diagramDependencyGraph(profile: RepoProfile): string {
  const nodes = profile.topLevelDirs.length
    ? profile.topLevelDirs
    : ["module_a", "module_b"];
  const root = nodes[0]!;
  const edges = nodes
    .slice(1)
    .map((node) => `  ${sanitize(root)} --> ${sanitize(node)}`)
    .join("\n");
  return `flowchart LR
${nodes.map((node) => `  ${sanitize(node)}[${node}]`).join("\n")}
${edges}
`;
}

export function diagramBlastRadius(): string {
  return `flowchart TD
  Change[Risky change] --> A[Affected module]
  A --> B[Downstream consumer]
  A --> C[Integration contract]
`;
}

export function wrapper(tool: string): string {
  return `# ${tool} — Contextum wrapper

This repository uses **Contextum**. Do not duplicate instructions here.

**Read \`${CANONICAL_AGENT_FILE}\` (the canonical source of truth) and the
\`${CONTEXT_DIR}/\` directory before changing code.**

Follow the read/update protocol defined in \`${CANONICAL_AGENT_FILE}\`.
`;
}



export function contextOrientationSkill(): string {
  return [
    "---",
    "name: context-orientation",
    "description: Orient through the Contextum AI context layer before any coding, review, planning, or debugging task. Use first to read the smallest reliable context set and avoid full-repository rediscovery.",
    "---",
    "",
    "# context-orientation",
    "",
    "Use this skill at the start of every coding, review, planning, or debugging task in a repository that uses Contextum.",
    "",
    "## Purpose",
    "",
    "Orient the agent through persistent engineering memory before touching source code. The goal is to read the smallest reliable context set, verify it against code, and avoid full-repository rediscovery unless the context is stale or insufficient.",
    "",
    "## Required read order",
    "",
    "1. `AGENTS.md`",
    "2. `ai-context/README.md`",
    "3. `ai-context/context.yml`",
    "4. `ai-context/code-map.md`",
    "5. `ai-context/integrations.md`",
    "6. `ai-context/business-features.md`",
    "7. `ai-context/change-impact.md` for risky changes",
    "8. `ai-context/repository-boundaries.md` when scope is unclear",
    "9. `ai-context/decisions.md` when architecture is involved",
    "10. `ai-context/unknowns.md` when facts are missing",
    "",
    "## Task routing",
    "",
    "- Feature work: read business-features, code-map, change-impact, repository-boundaries.",
    "- Integration work: read integrations, runtime, data-model, change-impact.",
    "- Runtime or deployment work: read runtime, integrations, architecture-flows, freshness.",
    "- Data changes: read data-model, change-impact, decisions, unknowns.",
    "- Review work: read change-impact, decisions, integrations, modified files only.",
    "- Context maintenance: read freshness, lifecycle, unknowns, context.yml.",
    "",
    "## Navigation",
    "",
    "- Use `ai-context/diagrams/code-graph.mmd` and `code-graph.json` (when present) to find modules and trace dependencies quickly instead of scanning the whole repository.",
    "- Use `ai-context/diagrams/code-symbols.json` to locate where a function, class, or type is defined by name.",
    "- Read `ai-context/relationships.md` for non-obvious cross-cutting links (shared invariants, implicit contracts, hidden coupling) that the graph cannot show.",
    "- Check existing repository docs (README, docs/, ADRs) before re-deriving facts.",
    "",
    "## Operating rules",
    "",
    "- Do not treat generated context as truth until verified against source code.",
    "- Prefer low confidence over invented certainty.",
    "- Add unknowns to `ai-context/unknowns.md` instead of guessing.",
    "- Update the relevant context files after behavior, contracts, architecture, or structure changes.",
  ].join("\n") + "\n";
}

const ROLE_DESCRIPTIONS: Record<string, string> = {
  "context-auditor":
    "Audit the Contextum context layer for drift, missing facts, and stale assumptions. Use to assess context quality; does not modify product code.",
  "implementation-agent":
    "Implement scoped code changes guided by the Contextum context layer. Use for feature work and fixes that must respect repository boundaries.",
  reviewer:
    "Review-only agent. Use after implementation to review a diff for correctness, safety, concurrency, and contract risk. Never modifies code.",
  "context-maintainer":
    "Maintain the AI context layer after code or architecture changes. Use to update freshness, code-map, integrations, decisions, and unknowns.",
};

export function rolePrompt(name: string): string {
  const frontmatter = [
    "---",
    `name: ${name}`,
    `description: ${ROLE_DESCRIPTIONS[name] ?? `Contextum ${name} role. Read AGENTS.md and ai-context/ before acting.`}`,
    "---",
    "",
  ];

  const bodies: Record<string, string[]> = {
    "context-auditor": [
      "# context-auditor",
      "",
      "Audit the Contextum layer for drift, missing facts, stale assumptions, and weak confidence.",
      "",
      "## Responsibilities",
      "",
      "- Compare `ai-context/` against the current repository structure.",
      "- Identify stale or missing business, runtime, integration, and data-model context.",
      "- Update `ai-context/unknowns.md` with unresolved questions.",
      "- Recommend lifecycle changes in `ai-context/lifecycle.md`.",
      "",
      "## Boundaries",
      "",
      "Do not implement product code. Report context quality issues and propose context updates.",
    ],
    "implementation-agent": [
      "# implementation-agent",
      "",
      "Implement scoped code changes using Contextum before reading broad source areas.",
      "",
      "## Responsibilities",
      "",
      "- Read `AGENTS.md` and the relevant `ai-context/` files before editing.",
      "- Keep changes inside repository boundaries.",
      "- Verify context against source code before relying on it.",
      "- Update context files when behavior, structure, or contracts change.",
      "",
      "## Boundaries",
      "",
      "Do not silently expand scope. Log unknowns when the context is insufficient.",
    ],
    reviewer: [
      "# reviewer",
      "",
      "Review-only agent for Contextum repositories.",
      "",
      "## Responsibilities",
      "",
      "- Review diffs for correctness, safety, concurrency, data integrity, security, and contract risk.",
      "- Use `ai-context/change-impact.md`, `integrations.md`, `data-model.md`, and `decisions.md` to reason about blast radius.",
      "- Report findings with file and line references where possible.",
      "",
      "## Boundaries",
      "",
      "Do not modify code. Do not rewrite the implementation. Findings first, summaries second.",
    ],
    "context-maintainer": [
      "# context-maintainer",
      "",
      "Maintain the repository AI Context Layer after code or architecture changes.",
      "",
      "## Responsibilities",
      "",
      "- Update `ai-context/freshness.md` and changelog entries.",
      "- Update `code-map.md` when structure changes.",
      "- Update `business-features.md` when behavior changes.",
      "- Update `integrations.md` when contracts change.",
      "- Update `decisions.md` when architecture decisions are made.",
      "- Keep `unknowns.md` honest.",
      "",
      "## Boundaries",
      "",
      "Do not invent facts. Mark unverified facts as UNKNOWN.",
    ],
  };

  const body = bodies[name] ?? [
    "# " + name,
    "",
    "Generic Contextum role. Read AGENTS.md and ai-context/ before acting.",
  ];

  return [...frontmatter, ...body].join("\n") + "\n";
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}
